name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "this is working"
      - name: print goodBye
        run: echo "all of this is ok"
      
